# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [2]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [3]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [4]:
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [5]:
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [7]:
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [8]:
X = data.iloc[:, :-1]   #  as features, we are selecting all columns except the last one
y = data.iloc[:, -1]    # given that target variable is the last variable (column) in the dataset

In [9]:
display(X)
display(y)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)     # splitting training into 80%-20%

# random_state=42; makes the split reproducible, so we get the same result each time we run the code
# to ensure consistency for training and debugging purposes

# test_size=0.2 means 80% training data and 20% testing data

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [11]:
from sklearn.linear_model import LinearRegression    # importing the Linear Regression model from scikit-learn

lin_reg = LinearRegression()   # creating tan empty Linear Regression model (no learning happened at this stage yet)

lin_reg.fit(X_train, y_train)        # training the model, so it sees how X_train (the training features) relate to y_train (the correct target values)

y_train_pred = lin_reg.predict(X_train)  # asking the model to predict the target values for the training data to check how weel the model learned from the data it studied

y_test_pred = lin_reg.predict(X_test)  # asking the model to predict the target values for the test data, to see how well the model performs on new, unseen data

## 3. Calculate and print R-squared for both the training and the testing set.

In [12]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

r2_train = r2_score(y_train, y_train_pred)   # comparing the real training answers with the model’s training predictions; checks how well the model explains the data it learned from

r2_test = r2_score(y_test, y_test_pred) # comparing the real test answers with the model’s test predictions; checking how well the model explains new, unseen data

print("Training R_squared is:", r2_train)
print("Testing R_squared is:", r2_test)

Training R_squared is: 0.7508856358979672
Testing R_squared is: 0.6687594935356289

In [ ]:
# R_squared tells us how much of the variation in y is explained by the model.

# Training R_squared -> how well the model fits the data it learned from; i.e., did the model lear the training examples well?

# Testing R_squared -> how well the model performs on new, unseen data; i.e., can the model generalise to data it did not study?

In [ ]:
# Good model:
# Training R_squared and Testing R_squared are both reasonably high and close together.

# Overfitting:
# Training R_squared is much higher than Testing R_squared.

# Weak model:
# Both Training R_squared and Testing R_squared are low.

# Bad model:
# Testing R_squared is around 0 or negative.

# R² value   | Interpretation            
################################################
# 0.90–1.00  | Very strong                       
# 0.75–0.90  | Good                              
# 0.50–0.75  | Moderate                          
# 0.20–0.50  | Weak                              
# Around 0   | No real predictive value          
# Below 0    | Worse than predicting the average

In [32]:
abs(r2_train-r2_test)

0.08212614236233828

In [ ]:
r2_difference = abs(r2_train - r2_test)

if r2_difference < 0.05:
    print("Very close: train and test R_squared are well balanced. This means that training R_squared and testing R_squared are almost the same. The model performs similarly on practice data and new data.")
elif r2_difference < 0.10:
    print("Usually acceptable: small difference between train and test R_squared. The model does a bit better on training data than test data, which is normal. OK, especially for a first model.")
elif r2_difference < 0.20:
    print("Watch carefully: possible overfitting or instability. The model may be starting to fit the training data more than the test data.")
else:
    print("Large gap: possible overfitting. The model performs much better on training data than test data. The model may have learned the training data too specifically and struggles with new data. The model learns the training data too closely, including noise or details that do not generalise.")
    
print(r2_difference)

# Underfitting means the model is too simple 
# and does not learn the pattern well. The model did not memorise the data, 
# but it also did not understand the relationship well enough.

Usually acceptable: small difference between train and test R_squared. The model does a bit better on training data than test data, which is normal. OK, especially for a first model.
0.08212614236233828

In [ ]:
# So, the model explains about 67% of the variation in the target for unseen data.

# This is moderate to reasonably good (acceptable gap of 0.08), especially for a first Linear Regression model.

# The model has a reasonable fit. The training and testing R² values are fairly close, so overfitting does not appear to be a major issue. 
# The testing R_squared of around 0.67 suggests the model has moderate predictive power, 
# but there is still room for improvement.

# It is worth comparing with another model later.

## 4. Calculate and print mean squared error for both the training and the testing set.

In [38]:
mse_train = mean_squared_error(y_train, y_train_pred)  # comparing the real training values with the model’s training predictions; i.e., how large are the model’s errors on the data it learned from?
mse_test = mean_squared_error(y_test, y_test_pred)  # comparing the real test values with the model’s test predictions; i.e., how large are the model’s errors on new unseen data?

print("Training MSE is:", mse_train)
print("Testing MSE is:", mse_test)

Training MSE is: 21.641412753226316
Testing MSE is: 24.29111947497374

In [ ]:
# Looking into the RMSE for easier interpretation, given that the MSE is squared.

# RMSE will therefore be in the same unit as the target value. Hence:

rmse_train = np.sqrt(mse_train)
rmse_test = np.sqrt(mse_test)

print("Training RMSE is :", rmse_train)
print("Testing RMSE is:", rmse_test)

Training RMSE is : 4.6520331848801675
Testing RMSE is: 4.928602182665359

In [40]:
y_test.mean()

np.float64(21.488235294117644)

In [42]:
# Comparing RMSE with y_test mean percentage wise:

rmse_test_percent = (rmse_test / y_test.mean()) * 100
rmse_test_percent

np.float64(22.93628171511391)

In [ ]:
# The model is usable as a first baseline, but its predictions still have noticeable error (23%).

# So combining the R_squared data with the RMSE data, we see that 
# the model generalises reasonably well, but its prediction accuracy is only moderate. 
# It is a decent first Linear Regression baseline, not a final strong model.

# RMSE as % of average target | Interpretation 
################################################
#                     < 10%   | Strong        
#                    10–20%   | Reasonable     
#                    20–30%   | Weak/moderate  
#                    > 30%    | Poor

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [ ]:
mae_train = mean_absolute_error(y_train, y_train_pred)
mae_test = mean_absolute_error(y_test, y_test_pred)

print("Training MAE:", mae_train)   # comparing the real training values with the model’s training predictions.
print("Testing MAE:", mae_test)    # comparing the real test values with the model’s test predictions

Training MAE: 3.314771626783233
Testing MAE: 3.189091965887874

In [44]:
mae_test_percent = (mae_test / y_test.mean()) * 100
print("Testing MAE as % of average target:", mae_test_percent)

Testing MAE as % of average target: 14.841106876565528

In [ ]:
# MAE as % of average target | Interpretation 
############################################# 
#                     < 10%  | Strong         
#                    10–20%  | Reasonable     
#                    20–30%  | Weak/moderate  
#                     > 30%  | Poor

In [ ]:
# On average:

# Training predictions are wrong by about 3.31 units.
# Testing predictions are wrong by about 3.19 units.

# The MAE values are very close, so there is no sign of overfitting from MAE. 
# The model is typically wrong by about 3.2 units, and whether that is good depends 
# on how large the target values usually are.

## Classification Model Evaluation

In [15]:
from sklearn.datasets import load_iris
data = load_iris()

In [16]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [ ]:
column_names = data.feature_names

# column names for the input features

In [ ]:
df = pd.DataFrame(data['data'],columns=column_names)

# converting the feature values into a proper Pandas DataFrame

In [19]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
target = pd.DataFrame(data.target)

# actual class labels as numbers (the answers, i.e., the categories we want to predict)

In [ ]:
data.keys()

# showing what information is inside the dataset object

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
data['target_names']

# what the numbers mean

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [48]:
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
)

In [50]:
import pandas as pd

y = pd.Series(data.target)
print(y.value_counts())

0    50
1    50
2    50
Name: count, dtype: int64

In [51]:
print(np.unique(y, return_counts=True))

(array([0, 1, 2]), array([50, 50, 50]))

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [52]:
from sklearn.linear_model import LogisticRegression

# Creating the model:
log_reg = LogisticRegression(max_iter=200)

# Training the model:
log_reg.fit(X_train, y_train)

# Predictions from the model:
y_train_pred = log_reg.predict(X_train)
y_test_pred = log_reg.predict(X_test)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [ ]:
from sklearn.metrics import accuracy_score

# Accuracy calculation:
accuracy_train = accuracy_score(y_train, y_train_pred)
accuracy_test = accuracy_score(y_test, y_test_pred)

print("Training Accuracy is:", accuracy_train)
print("Testing Accuracy is:", accuracy_test)

Training Accuracy: 0.975
Testing Accuracy: 1.0

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [54]:
from sklearn.metrics import balanced_accuracy_score

# Balanced Accuracy calculation:
bal_acc_train = balanced_accuracy_score(y_train, y_train_pred)
bal_acc_test = balanced_accuracy_score(y_test, y_test_pred)

print("Training Balanced Accuracy is:", bal_acc_train)
print("Testing Balanced Accuracy is:", bal_acc_test)

Training Balanced Accuracy is: 0.975609756097561
Testing Balanced Accuracy is: 1.0

## 10. Calculate and print the precision score for both the training and the testing set.

In [ ]:
from sklearn.metrics import precision_score

# Precision (using average="macro" for multi-class):
precision_train = precision_score(y_train, y_train_pred, average="macro")
precision_test = precision_score(y_test, y_test_pred, average="macro")

print("Training Precision is:", precision_train)
print("Testing Precision is:", precision_test)

Training Precision: 0.9761904761904763
Testing Precision: 1.0

## 11. Calculate and print the recall score for both the training and the testing set.

In [ ]:
from sklearn.metrics import recall_score

# Recall (using average="macro" for multi-class)
recall_train = recall_score(y_train, y_train_pred, average="macro")
recall_test = recall_score(y_test, y_test_pred, average="macro")

print("Training Recall is:", recall_train)
print("Testing Recall is:", recall_test)

Training Recall: 0.975609756097561
Testing Recall: 1.0

## 12. Calculate and print the F1 score for both the training and the testing set.

In [ ]:
from sklearn.metrics import f1_score

# F1 Score (using average="macro" for multi-class)
f1_train = f1_score(y_train, y_train_pred, average="macro")
f1_test = f1_score(y_test, y_test_pred, average="macro")

print("Training F1 Score is:", f1_train)
print("Testing F1 Score is:", f1_test)

Training F1 Score: 0.974996093139553
Testing F1 Score: 1.0

## 13. Generate confusion matrices for both the training and the testing set.

In [58]:
from sklearn.metrics import confusion_matrix

# Confusion matrices
cm_train = confusion_matrix(y_train, y_train_pred)
cm_test = confusion_matrix(y_test, y_test_pred)

print("Training Confusion Matrix:\n", cm_train)
print("\nTesting Confusion Matrix:\n", cm_test)

Training Confusion Matrix:
 [[40  0  0]
 [ 0 38  3]
 [ 0  0 39]]

Testing Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [31]:
# Have fun here !